print('You will be ' + str(int(18+1)) + ' in a year.')
#in lên màn hình "you will be", Str là type text, int là số nguyên 
print('You will be ' + str(int('18') + 1 ) + ' in a year.')
print('You will be ' + str(18+1) + ' in a year.')
print('You will be ' + str(19) + ' in a year.')
print('You will be ' + '19' + ' in a year.')
print('You will be 19 ' + 'in a year.')
print('You will be 19 in a year.')
